name: Documentation Generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docfx-action
      uses: nikeee/docfx-action@v0.1.0
      with:
        args: TransITGeometryTransfer-Revit/TransITGeometryTransferRevit/docfx.json -t statictoc

    - uses: actions/upload-artifact@v2
      with:
        name: api-documentation-${{ github.sha }}
        path: TransITGeometryTransfer-Revit/TransITGeometryTransferRevit/_site
